const faculty = [
  {
    id: 1,
    name: "Dr. Payal Pahwa",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image:"/BPIT-Principal-150x150.jpg",
    researchInterest :`Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    title: "Professor of Information Technology",
    department: "IT",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Network Security & Cloud Computing",
    publications: 89,
    awards: 8,
    students: 32,
    bio: "Expert in network security and cloud infrastructure, with a decade of teaching experience.",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    title: "Professor of Electronics & Communication",
    department: "ECE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Signal Processing & Embedded Systems",
    publications: 120,
    awards: 15,
    students: 28,
    bio: "Pioneer in signal processing and embedded systems, with multiple international patents.",
  },
  {
    id: 7,
    name: "Dr. Payal Pahwa 2",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image: "/BPIT-Principal-150x150.jpg",
    researchInterest: `Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 8,
    name: "Dr. Payal Pahwa 3",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image: "/BPIT-Principal-150x150.jpg",
    researchInterest: `Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    title: "Professor of Electrical Engineering",
    department: "EEE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Power Systems & Automation",
    publications: 95,
    awards: 10,
    students: 38,
    bio: "Renowned for research in power systems and industrial automation.",
  },
  {
    id: 5,
    name: "Dr. Priya Sharma",
    title: "Professor of Management",
    department: "MBA",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Strategic Management & Innovation",
    publications: 60,
    awards: 7,
    students: 25,
    bio: "Specialist in strategic management and business innovation, with industry and academic experience.",
  },
  {
    id: 6,
    name: "Dr. Rajat Mehra",
    title: "Professor of Business Administration",
    department: "BBA",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Marketing & Entrepreneurship",
    publications: 40,
    awards: 5,
    students: 20,
    bio: "Entrepreneurship mentor and marketing expert, passionate about student startups.",
  },
];
export default faculty;