const faculty = [
  {
    id: 1,
    name: "Dr. Payal Pahwa",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image:"/BPIT-Principal-150x150.jpg",
    researchInterest :`Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    title: "Professor of Information Technology",
    department: "IT",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Network Security & Cloud Computing",
    publications: 89,
    awards: 8,
    students: 32,
    bio: "Expert in network security and cloud infrastructure, with a decade of teaching experience.",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    title: "Professor of Electronics & Communication",
    department: "ECE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Signal Processing & Embedded Systems",
    publications: 120,
    awards: 15,
    students: 28,
    bio: "Pioneer in signal processing and embedded systems, with multiple international patents.",
  },
  {
    id: 7,
    name: "Dr. Payal Pahwa 2",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image: "/BPIT-Principal-150x150.jpg",
    researchInterest: `Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 8,
    name: "Dr. Payal Pahwa 3",
    title: "PROFESSOR & Principal",
    department: "CSE",
    image: "/BPIT-Principal-150x150.jpg",
    researchInterest: `Research Intrest: Data Warehousing, Big data`,
    publications: 68,
    bio: `Years Of Experience: 29+
          Qualification: Ph.D(CSE) JNU, M.S. (CSE)`,
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    title: "Professor of Electrical Engineering",
    department: "EEE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Power Systems & Automation",
    publications: 95,
    awards: 10,
    students: 38,
    bio: "Renowned for research in power systems and industrial automation.",
  },
  {
    id: 5,
    name: "Dr. Priya Sharma",
    title: "Professor of Management",
    department: "MBA",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Strategic Management & Innovation",
    publications: 60,
    awards: 7,
    students: 25,
    bio: "Specialist in strategic management and business innovation, with industry and academic experience.",
  },
  {
    id: 6,
    name: "Dr. Rajat Mehra",
    title: "Professor of Business Administration",
    department: "BBA",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Marketing & Entrepreneurship",
    publications: 40,
    awards: 5,
    students: 20,
    bio: "Entrepreneurship mentor and marketing expert, passionate about student startups.",
  },
  {
    id: 9,
    name: "Dr. Ananya Gupta",
    title: "Associate Professor of Computer Science",
    department: "CSE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Machine Learning & Artificial Intelligence",
    publications: 75,
    awards: 12,
    students: 45,
    bio: "Expert in machine learning algorithms and AI applications, with focus on deep learning and neural networks.",
  },
  {
    id: 10,
    name: "Dr. Vikram Singh",
    title: "Professor of Electronics & Communication",
    department: "ECE",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "VLSI Design & Embedded Systems",
    publications: 85,
    awards: 9,
    students: 35,
    bio: "Specialist in VLSI design and embedded systems, with extensive industry collaboration experience.",
  },
  {
    id: 11,
    name: "Dr. Kavita Sharma",
    title: "Associate Professor of Information Technology",
    department: "IT",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Database Systems & Data Analytics",
    publications: 55,
    awards: 6,
    students: 30,
    bio: "Database expert and data analytics specialist, with focus on big data technologies and business intelligence.",
  },
  {
    id: 12,
    name: "Shri Vinod Vats",
    title: "Chairman",
    department: "Management",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Educational Leadership & Social Work",
    publications: 0,
    awards: 15,
    students: 0,
    bio: "Chairman of Bhagwan Parshuram Institute of Technology and President of Bhartiya Brahmin Charitable Trust. A visionary leader with extensive experience in educational administration and social work.",
  },
  {
    id: 13,
    name: "Shri Surender Sharma",
    title: "Vice President",
    department: "Management",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Literature & Cultural Affairs",
    publications: 0,
    awards: 25,
    students: 0,
    bio: "Padma Shri awardee, renowned Hindi poet (Hasyakavi) and Vice President of BPIT. Popular across the globe for his humorous renditions and literary contributions.",
  },
  {
    id: 14,
    name: "Shri Ram Babu Sharma",
    title: "General Secretary",
    department: "Management",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Administration & Social Services",
    publications: 0,
    awards: 8,
    students: 0,
    bio: "General Secretary of BPIT with extensive experience in social, religious and sports organizations. Active in educational and charitable initiatives.",
  },
  {
    id: 15,
    name: "Shri Shambhu Sharma",
    title: "Secretary",
    department: "Management",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Healthcare Administration & Social Work",
    publications: 0,
    awards: 12,
    students: 0,
    bio: "Secretary of BPIT, Director of Brahm Shakti Sanjeevani and MLS hospitals. Philanthropist and active social worker with extensive organizational experience.",
  },
  {
    id: 16,
    name: "Shri Sanjeev Sharma",
    title: "Treasurer",
    department: "Management",
    image: "/placeholder.svg?height=300&width=300",
    specialization: "Financial Management & Educational Administration",
    publications: 0,
    awards: 10,
    students: 0,
    bio: "Treasurer of BPIT with strong belief in holistic education. Focuses on developing students' creative thinking, articulation, novelty and teamwork through dedicated faculty and infrastructure.",
  },
];
export default faculty;